---

learning_rate: 0.001
batch_size: 10
max_epochs: 10
crop_height: 256
crop_width: 256
split_name: 'split_1'
cell_mask_model_path: 'C:/Users/Marcel/Desktop/models/maxvit_smal_tf_224_256x256_batch20_epoch200/model.ckpt'